import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:flutter_quill/quill_delta.dart';

String initText(QuillController _controller) {
  try {
    var mainText = new Delta()
      ..insert("Identificação")
      ..insert("\n")
      ..insert("Escola")
      ..insert("\n")
      ..insert("XXXX")
      ..insert("\n")
      ..insert("Professor (a)")
      ..insert("\n")
      ..insert("JARDEANE DE SOUZA SILVA")
      ..insert("\n")
      ..insert("Disciplina ")
      ..insert("\n")
      ..insert("ENSINO DE LIBRAS")
      ..insert("\n")
      ..insert("Ano")
      ..insert("\n")
      ..insert("4º ANO")
      ..insert("\n")
      ..insert("Turno: TARDE")
      ..insert("\n")
      ..insert("Aluno (a) incluído (a)")
      ..insert("\n")
      ..insert("(   ) Surdo")
      ..insert("\n")
      ..insert("(   ) Deficiente Auditivo")
      ..insert("\n")
      ..insert("(   ) Cego")
      ..insert("\n")
      ..insert("(   ) Baixa Visão")
      ..insert("\n")
      ..insert("(   ) Surdocego")
      ..insert("\n")
      ..insert("(   ) TEA Transtorno do Espectro Autista")
      ..insert("\n")
      ..insert("(   ) Deficiência Intelectual")
      ..insert("\n")
      ..insert("(   ) Síndrome de Down")
      ..insert("\n")
      ..insert("(   ) Altas Habilidades")
      ..insert("\n")
      ..insert("Recursos de acessibilidade")
      ..insert("\n")
      ..insert("Livro acessível; LSE; TILS")
      ..insert("\n")
      ..insert("Sala de Recursos Multifuncionais")
      ..insert("\n")
      ..insert("(   ) Sim")
      ..insert("\n")
      ..insert("(   ) Não")
      ..insert("\n")
      ..insert("Estratégias de promoção da aprendizagem em sala de aula")
      ..insert("\n")
      ..insert(
          "(   ) Proporcionar situações de apoio individualizado na sala de aula. Responsável pelo apoio: TILS")
      ..insert("\n")
      ..insert("(   ) Promover ações de tutorias entre os estudantes")
      ..insert("\n")
      ..insert("(   ) Atividades para casa")
      ..insert("\n")
      ..insert("(   ) Atividades cooperativas em sala de aula")
      ..insert("\n")
      ..insert(
          "(   ) Realizar revisões de conteúdos anteriores no começo da aula")
      ..insert("\n")
      ..insert(
          "(   ) Planejamento de resoluções de problemas de forma colaborativa")
      ..insert("\n")
      ..insert("(   ) Promoção da autoavaliação")
      ..insert("\n")
      ..insert("(   ) Correção coletiva das atividades e avaliações")
      ..insert("\n")
      ..insert("(   ) Promoção de conflitos sociocognitivos")
      ..insert("\n")
      ..insert("(   ) Outras")
      ..insert("\n")
      ..insert("Plano de Aula")
      ..insert("\n")
      ..insert("Tema da Aula")
      ..insert("\n")
      ..insert("Antônimos")
      ..insert("\n")
      ..insert("Objetivos da aula (de aprendizagem e desenvolvimento)")
      ..insert("\n")
      ..insert("Discutir os Antônimos em Libras;")
      ..insert("\n")
      ..insert("Aumentar o vocabulário em Libras")
      ..insert("\n")
      ..insert("Relacionar os antônimos em libras de acordo com o cotidiano")
      ..insert("\n")
      ..insert("Conteúdo")
      ..insert("\n")
      ..insert("Conceituais: Antônimos em Libras")
      ..insert("\n")
      ..insert("Procedimentais: Identificar os Antônimos em Libras")
      ..insert("\n")
      ..insert("Atitudinais: Uso de Antônimos em Libras no cotidiano.")
      ..insert("\n")
      ..insert("Pergunta (s) essencial (is) da aula")
      ..insert("\n")
      ..insert("Como usamos os Antônimos no nosso cotidiano")
      ..insert("\n")
      ..insert("Palavras-chave")
      ..insert("\n")
      ..insert("Antônimos – Libras - Cotidiano")
      ..insert("\n")
      ..insert("Competência a ser desenvolvida (BNCC)")
      ..insert("\n")
      ..insert(
          "Utilizar diferentes linguagens – verbal (oral ou visual-motora, como Libras, e escrita), corporal, visual, sonora e digital –, para se expressar e partilhar informações, experiências, ideias e sentimentos em diferentes contextos e produzir sentidos que levem ao diálogo, à resolução de conflitos e à cooperação.")
      ..insert("\n")
      ..insert("Habilidade (s) da BNCC")
      ..insert("\n")
      ..insert(
          "(EF02LP10) Identificar sinônimos de palavras de texto lido, determinando a diferença de sentido entre eles, e formar antônimos de palavras encontradas em texto lido pelo acréscimo do prefixo de negação in-/im-.")
      ..insert("\n")
      ..insert("Recursos didático-pedagógicos para esta aula")
      ..insert("\n")
      ..insert(
          "Vídeos do youtube; Livro acessível; Jogo da Memória com Antônimos em Libras")
      ..insert("\n")
      ..insert("Uso de Tecnologias Assistivas")
      ..insert("\n")
      ..insert("-")
      ..insert("\n")
      ..insert("Objetos Educacionais Digitais (OEDs)")
      ..insert("\n")
      ..insert("-")
      ..insert("\n")
      ..insert(
          "Estratégias mediadoras em sala de aula para trabalhar o conteúdo desta aula")
      ..insert("\n")
      ..insert(
          "(   ) Mediação individual (professor) nas atividades e avaliações.")
      ..insert("\n")
      ..insert("(   ) Trabalhar os conceitos/conteúdos no concreto.")
      ..insert("\n")
      ..insert(
          "(   ) Proporcionar tempo estendido para realização de atividades e avaliações.")
      ..insert("\n")
      ..insert("(   ) Reduzir textos e enunciados para melhor compreensão.")
      ..insert("\n")
      ..insert("(   ) Questões objetivas.")
      ..insert("\n")
      ..insert("(   ) Correção diferenciada nas avaliações.")
      ..insert("\n")
      ..insert("(   ) Adaptação curricular.")
      ..insert("\n")
      ..insert("Procedimentos Didático-metodológicos")
      ..insert("\n")
      ..insert("Desenvolvimento do tema")
      ..insert("\n")
      ..insert(
          "Vou apresentar o Vídeo do Youtube: https://www.youtube.com/watch?v=NfprdgxxeWU – o que são Antônimos?.")
      ..insert("\n")
      ..insert(
          "Questionar o que o Vídeo conceitua o que é Antônimo? Então podemos utilizar os Antônimos no nosso cotidiano?")
      ..insert("\n")
      ..insert(
          "Pedir para que os alunos sinalizem quais Antônimos que conhecemos no nosso cotidiano.")
      ..insert("\n")
      ..insert("Trabalhar o Jogo da Memória com Antônimos em Libras")
      ..insert("\n")
      ..insert(
          "Atividades pedagógicas que serão desenvolvidas para promover experiências de aprendizagem")
      ..insert("\n")
      ..insert("Atividades em grupo para trabalhar o Jogo da Memória.")
      ..insert("\n")
      ..insert(
          "Modelo de Ação (operações) para a realização da atividade pedagógica")
      ..insert("\n")
      ..insert("Trabalho em grupo.")
      ..insert("\n")
      ..insert("Cooperação.")
      ..insert("\n")
      ..insert("Colaboração.")
      ..insert("\n")
      ..insert("Avaliação")
      ..insert("\n")
      ..insert("Formativa e processual.")
      ..insert("\n")
      ..insert("Modelo de Controle (autoavaliação)")
      ..insert("\n")
      ..insert(
          "Os alunos irão falar sobre as aprendizagens do dia de forma coletiva.")
      ..insert("\n")
      ..insert("Formas de registro da avaliação")
      ..insert("\n")
      ..insert(
          "Os alunos irão gravar um vídeo em Libras usando os Antônimos que foram aprendidos na aula.")
      ..insert("\n")
      ..insert("Referências")
      ..insert("\n")
      ..insert(
          "BRASIL. Base Nacional Comum Curricular (BNCC). Educação é a Base. Brasília, MEC/CONSED/UNDIME, 2017. Disponível em: <http://basenacionalcomum.mec.gov.br/images/BNCC_EI_EF_110518_versaofinal_site.pdf>. Acesso em 24/07/2020.")
      ..insert("\n");

    // var initialText = new Delta()
    //   ..insert("Objetivo geral")
    //   ..insert("\n", {"list": "bullet", "color": "black"})
    //   ..insert(
    //       "Ao final desta aula espera-se que o(s) aluno(s) esteja(m) apto(s) a...")
    //   ..insert("\n", {"list": "bullet", "indent": 1})
    //   ..insert("Objetivos especificos")
    //   ..insert("\n", {"list": "bullet"})
    //   ..insert(
    //       "Para alcançar o objetivo geral, o(s) aluno(s) deve(m) aprender a ou sobre...")
    //   ..insert("\n", {"list": "bullet", "indent": 1})
    //   ..insert("Metodologia")
    //   ..insert("\n", {"list": "bullet"})
    //   ..insert(
    //       "Descreva detalhadamente como executar os objetivos específicos (como se fosse um manual de instruções). Explicite quais recursos utilizar e como utilizá-los.")
    //   ..insert("\n", {"list": "bullet", "indent": 1})
    //   ..insert("Avaliação")
    //   ..insert("\n", {"list": "bullet"})
    //   ..insert(
    //       "Como você pretende avaliar/verificar se o(s) aluno(s) alcançou(aram) o objetivo específico?")
    //   ..insert("\n", {"list": "bullet", "indent": 1})
    //   ..insert("Recursos")
    //   ..insert("\n", {"list": "bullet"})
    //   ..insert("Quais os materiais você vai precisar para executar sua aula?")
    //   ..insert("\n", {"list": "bullet", "indent": 1})
    //   ..insert("Referências")
    //   ..insert("\n", {"list": "bullet"})
    //   ..insert(
    //       "Para que outro professor possa se preparar para executar sua proposta de aula, nos diga: De onde você tirou toda sua inspiração? (livros, revistas, sites, outros planos de aula)")
    //   ..insert("\n", {"list": "bullet", "indent": 1});

    _controller.compose(mainText,
        TextSelection.collapsed(offset: mainText.length), ChangeSource.local);

    return _controller.document.toPlainText();
  } catch (err, st) {
    print('Cannot read welcome.json: $err\n$st');
    _controller = _controller;
    return '';
  }
}
